services:
  - type: web
    name: million-dollar-nft-page
    env: docker
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: MAX_IMAGES
        value: 1000000
      - key: PRICE_PER_IMAGE
        value: 5.00
      - key: USDC_WALLET_ADDRESS
        sync: false
      - key: ADMIN_WALLET_ADDRESS
        sync: false
